name: CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Build
      run: dotnet build --configuration Release 

    - name: Test
      run: dotnet test --configuration Release

    - name: Publish
      run: dotnet publish BloodSugarTracking/BloodSugarTracking.csproj --configuration Release -o BloodSugarTracking/bin/publish

    - name: Create docker image
      run: docker build -f BloodSugarTracking/Dockerfile -t bloodsugartracking:2.0.0 .

  github-package-docker-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    name: GitHub package docker push
    needs: build-test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish BloodSugarTracking/BloodSugarTracking.csproj --configuration Release -o BloodSugarTracking/bin/publish

    - name: Create docker image
      run: docker build -f BloodSugarTracking/Dockerfile -t ghcr.io/arnab-developer/bloodsugartracking/bloodsugartracking:2.0.0 .

    - name: Push docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Arnab-Developer --password-stdin
        docker push ghcr.io/arnab-developer/bloodsugartracking/bloodsugartracking:2.0.0
        docker logout ghcr.io

  dockerhub-push:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    name: Dockerhub push
    needs: build-test
    environment:
      name: Dockerhub
      url: https://hub.docker.com/r/45862391/bloodsugartracking

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish BloodSugarTracking/BloodSugarTracking.csproj --configuration Release -o BloodSugarTracking/bin/publish

    - name: Create docker image
      run: docker build -f BloodSugarTracking/Dockerfile -t 45862391/bloodsugartracking:2.0.0 .

    - name: Push docker image
      run: |
        echo "${{ secrets.DOCKERHUB_PWD }}" | docker login -u 45862391 --password-stdin
        docker push 45862391/bloodsugartracking:2.0.0
        docker logout
